/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_lmmetrics_free: (a: number, b: number) => void;
export const lmmetrics_epoch: (a: number) => number;
export const lmmetrics_epoch_progress: (a: number) => number;
export const lmmetrics_flops_per_second: (a: number, b: number) => number;
export const lmmetrics_format_flops: (a: number) => [number, number];
export const lmmetrics_learning_rate: (a: number) => number;
export const lmmetrics_loss_history_json: (a: number) => [number, number];
export const lmmetrics_new: () => number;
export const lmmetrics_reset: (a: number) => void;
export const lmmetrics_set_epoch: (a: number, b: number, c: number) => void;
export const lmmetrics_set_flops_per_step: (a: number, b: number) => void;
export const lmmetrics_start_timer: (a: number, b: number) => void;
export const lmmetrics_step: (a: number) => number;
export const lmmetrics_tokens_per_second: (a: number, b: number) => number;
export const lmmetrics_tokens_processed: (a: number) => number;
export const lmmetrics_train_loss: (a: number) => number;
export const lmmetrics_train_perplexity: (a: number) => number;
export const lmmetrics_update_train: (a: number, b: number, c: number, d: number, e: number) => void;
export const lmmetrics_update_val: (a: number, b: number) => void;
export const lmmetrics_val_loss: (a: number) => number;
export const lmmetrics_val_loss_history_json: (a: number) => [number, number];
export const lmmetrics_val_perplexity: (a: number) => number;
export const start: () => void;
export const __wbg_tokenprob_free: (a: number, b: number) => void;
export const tokenprob_id: (a: number) => number;
export const tokenprob_prob: (a: number) => number;
export const tokenprob_text: (a: number) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1fc26d4bc1559e26: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h4ca2343935473c97: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h36e18218b8010af8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6704984b19d5933d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9efbcc4b940797ad: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h7d0fb7af338d42f6: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd8f361f0f2db1dc8: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
